[local]
localhost

[mongodb]
mongodb.devops550.online

[redis]
redis.devops550.online

[mysql]
mysql.devops550.online

[rabbitmq]
rabbitmq.devops550.online

[catalogue] 
catalogue.devops550.online

[user]
user.devops550.online

[cart]
cart.devops550.online

[shipping]
shipping.devops550.online

[payment]
payment.devops550.online

[frontend]
frontend.devops550.online